apiVersion: v1
kind: Pod
metadata: 
  name: pod3
  labels:
    app: greetsvc
    tier: frontend
spec:
  containers:
    - name: frontend1
      image: greetingssvc:v2      
      ports:
      - containerPort: 8081
