apiVersion: v1
kind: Service
metadata:
  name: fendsvc
  labels:
    app: greetsvc
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8081
  selector:
    app: greetsvc
    tier: frontend
