CREATE DATABASE IF NOT EXISTS demodb;

use demodb;

CREATE TABLE IF NOT EXISTS  products (id INT PRIMARY KEY AUTO_INCREMENT, prdname VARCHAR(25) NOT NULL, prddesc VARCHAR(25) NOT NULL, prdprice DOUBLE NOT NULL);

