apiVersion: v1
kind: Pod
metadata: 
  name: pod2
  labels:
    app: greetsvc
    tier: backend
spec:
  containers:
    - name: backend1
      image: mysql-server-app:v1      
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: root
      - name: MYSQL_DATABASE
        value: demodb