apiVersion: v1
kind: Service
metadata:
  name: bendsvc
  labels:
    app: greetsvc
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: greetsvc
    tier: backend
